{
    'name': 'ATS Validator',
    'version': '19.0.1.0.0',
    'summary': 'Validación del Anexo Transaccional Simplificado (ATS) vía servicio externo',
    'category': 'Accounting/Accounting',
    'author': 'Nelio Ciguencia',
    'maintainer': 'Nelio Ciguencia',
    'website': 'https://github.com/nelio2120/odoo_ats_validator',
    'depends': ['account', 'base_setup', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequences.xml',
        'views/res_config_settings_views.xml',
        'views/ats_validation_views.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
